# -*- coding: utf-8 -*-
"""Decision tree for drugs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J0QH8sgdCGA78f-J_xUjm4YO2TonRljq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('drug200.csv')

data.info()

data.describe()

data.head()

data.tail()

data.shape

data.size

data.ndim

data.isnull()

data.isnull().sum()

data.columns

data['Na_to_K'] = data['Na_to_K'].round(0)
data['Na_to_K'].astype(int)

data.Cholesterol.replace({'HIGH': 1, 'NORMAL': 0}, inplace=True)
data.BP.replace({'HIGH': 1, 'NORMAL': 0, 'LOW': 2}, inplace=True)
data.Sex.replace({'M': 1, 'F': 0}, inplace=True)

from sklearn.model_selection import train_test_split

x=data[["Age","Sex","BP","Cholesterol","Na_to_K"]]
y=data["Drug"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)



age_value = data['Age'].value_counts()
top_age = age_value.head()
data_2 = pd.DataFrame({'Age': top_age.index, 'Count': top_age.values})

data_2

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

model = DecisionTreeClassifier()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
report = classification_report(y_test,y_pred)
print(report)

from sklearn.tree import plot_tree
unique_class=np.unique(y_train)
plt.figure(figsize=(20,10))
plot_tree(model,class_names=unique_class,filled=True)
plt.show()

