# -*- coding: utf-8 -*-
"""Decision Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJmPwcz48lMG6cQ1Kptkj1nGf2NYAU1W
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('bill_authentication.csv')

data.info()

data.describe()

data.size

data.shape

data.ndim

data.isnull()

data.isnull().sum()

data.head()

data.tail()

data.columns

from sklearn.model_selection import train_test_split

x= data[["Variance","Skewness", "Curtosis", "Entropy"]]
y= data["Class"]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)

print(x_train)

from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
scaler.fit(x_train)

x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

x_train

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

model=DecisionTreeClassifier()
model.fit(x_train,y_train)

y_pred = model.predict(x_test)
report = classification_report(y_test,y_pred)
print(report)

