# -*- coding: utf-8 -*-
"""GradientBoostingRegressor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oARMykG4ILjCQVuW59M_n6mUORjcdIm8
"""

import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import accuracy_score, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

file_path = '/content/House_Rent_Dataset.csv'
data = pd.read_csv(file_path)

data.head()

data.tail()

data.isnull().sum()

data.dropna

data.ndim

data.shape

data.size

data.info()

data.describe()

label_encoders = {}
for col in data.columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

x=data.drop(['Rent'],axis=1)
y=data['Rent']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)



model = GradientBoostingRegressor(n_estimators=1000, learning_rate=0.2, max_depth=2, random_state= 100)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

r2 = r2_score(y_test, y_pred)
print("R-squared Score:", r2)

y_pred

