# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhm92_2vLydp1lAVGyrZG4TM71Sbkm0n
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

data=pd.read_csv('house.csv')

data.info()

data.describe()

data.shape

data.size

data.ndim

data.head()

data.tail()

model=LinearRegression()

data.columns

x=data[['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated']]
y=data['price']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

sns.scatterplot(x=data['bedrooms'],y=data['price'])

model=LinearRegression()

from re import T
sns.heatmap(data.corr(numeric_only=True),cmap='viridis')

model.fit(x_train,y_train)

model.predict(x_test)

sns.boxplot(x=data['bedrooms'])

new_data=[[10000000,4,4,400,200,2,0,1,0,5,100,100,20]]

pri=model.predict(new_data)

print("price of the house is",pri)

