# -*- coding: utf-8 -*-
"""RandaomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VAAULcnUOgU_TIOJVg2Xd6J4gIDYTnM
"""

import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/content/studentRF.csv')

data['result']=data['result'].map({'pass':1,'fail':0})

data

x=data[['reg_no','marks']]
y=data['result']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=RandomForestClassifier(n_estimators=40,random_state=1)
model.fit(x_train,y_train)

pred = model.predict(x_test)
print("prediction : ",pred.tolist())
print("accuracy : ",accuracy_score(y_test,pred))

plt.figure(figsize=(8,5))
sns.scatterplot(x=x_test['reg_no'],y=x_test['marks'],hue=pred,style=y_test,s=100,palette="Set1")
plt.title('RandomForest vs Actual')
plt.xlabel('reg_no')
plt.ylabel('marks')
plt.legend(title='predicted (color)/Actual (shape)', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True)
plt.tight_layout()
plt.show()


importance=model.feature_importances_
feature_name=x.columns
plt.figure(figsize=(6,4))
sns.barplot(x=importance,y=feature_name,hue=pred,palette="viridis")
plt.title('Feature Importance')
plt.xlabel('Importance')
plt.ylabel('Features')
plt.tight_layout()
plt.show()

